// Original code created by Rinaldo

namespace FifaLibrary
{
  public class TI
  {
    private static string t_balls = nameof (balls);
    private static string t_career_extraplayerinfo = nameof (career_extraplayerinfo);
    private static string t_career_matchexperience = nameof (career_matchexperience);
    private static string t_career_suspensions = nameof (career_suspensions);
    private static string t_career_youthplayersattributes = nameof (career_youthplayerattributes);
    private static string t_career_youthplayershistory = nameof (career_youthplayerhistory);
    private static string t_formupdate = nameof (formupdate);
    private static string t_career_fixtureinfo = nameof (career_fixtureinfo);
    private static string t_fce_activeteams = nameof (fce_activeteams);
    private static string t_fce_weathersettings = nameof (fce_weathersettings);
    private static string t_fce_statistics = nameof (fce_statistics);
    private static string t_fce_standings = nameof (fce_standings);
    private static string t_fce_stageadvance = nameof (fce_stageadvance);
    private static string t_fce_settings = nameof (fce_settings);
    private static string t_fce_scriptfunctions = nameof (fce_scriptfunctions);
    private static string t_fce_scheduleinfo = nameof (fce_scheduleinfo);
    private static string t_fce_fixtures = nameof (fce_fixtures);
    private static string t_fce_competitionteams = nameof (fce_competitionteams);
    private static string t_fce_competitioninfo = nameof (fce_competitioninfo);
    private static string t_fce_compavgs = nameof (fce_compavgs);
    private static string t_fce_advancement = nameof (fce_advancement);
    private static string t_player_growth_experience_points = nameof (player_growth_experience_points);
    private static string t_player_career = nameof (player_career);
    private static string t_experiencepoints = nameof (experiencepoints);
    private static string t_finalstadiums = nameof (finalstadiums);
    private static string t_tourn_team_manager = nameof (tourn_team_manager);
    private static string t_tourn_settings = nameof (tourn_settings);
    private static string t_tourn_rtsg = nameof (tourn_rtsg);
    private static string t_tourn_manager_settings = nameof (tourn_manager_settings);
    private static string t_tourn_licensed_stages = nameof (tourn_licensed_stages);
    private static string t_tourn_licensed = nameof (tourn_licensed);
    private static string t_specialteams = nameof (specialteams);
    private static string t_achievements = nameof (achievements);
    private static string t_fifaUnlockables = nameof (fifaUnlockables);
    private static string t_usability = nameof (usability);
    private static string t_usability_functions = nameof (usability_functions);
    private static string t_virtualleagues = nameof (virtualleagues);
    private static string t_BigAttendance = nameof (BigAttendance);
    private static string t_MatchIntensity = nameof (MatchIntensity);
    private static string t_NoAttendance = nameof (NoAttendance);
    private static string t_assetcryptokeys = nameof (assetcryptokeys);
    private static string t_attributeprefpositionformula = nameof (attributeprefpositionformula);
    private static string t_audionation = nameof (audionation);
    private static string t_audiostadium = nameof (audiostadium);
    private static string t_career_blacklist = nameof (career_blacklist);
    private static string t_career_boardoutcomes = nameof (career_boardoutcomes);
    private static string t_career_calendar = nameof (career_calendar);
    private static string t_career_clinchedobjectives = nameof (career_clinchedobjectives);
    private static string t_career_commonnames = nameof (career_commonnames);
    private static string t_career_competitionprogress = nameof (career_competitionprogress);
    private static string t_career_firstnames = nameof (career_firstnames);
    private static string t_career_growthcurveinfo = nameof (career_growthcurveinfo);
    private static string t_career_lastnames = nameof (career_lastnames);
    private static string t_career_leagueballs = nameof (career_leagueballs);
    private static string t_career_loanbuy = nameof (career_loanbuy);
    private static string t_career_managerawards = nameof (career_managerawards);
    private static string t_career_managerhistory = nameof (career_managerhistory);
    private static string t_career_managerinfo = nameof (career_managerinfo);
    private static string t_career_managerpref = nameof (career_managerpref);
    private static string t_career_namesgroups = nameof (career_namesgroups);
    private static string t_career_news = nameof (career_news);
    private static string t_career_newsban = nameof (career_newsban);
    private static string t_career_newspicweights = nameof (career_newspicweights);
    private static string t_career_playasplayer = nameof (career_playasplayer);
    private static string t_career_playasplayerhistory = nameof (career_playasplayerhistory);
    private static string t_career_playerawards = nameof (career_playerawards);
    private static string t_career_playerbonusper = nameof (career_playerbonusper);
    private static string t_career_playercontract = nameof (career_playercontract);
    private static string t_career_playergrowthhistory = nameof (career_playergrowthhistory);
    private static string t_career_playergrowthupdates = nameof (career_playergrowthupdates);
    private static string t_career_playergrowthuserseason = nameof (career_playergrowthuserseason);
    private static string t_career_playermatchratinghistory = nameof (career_playermatchratinghistory);
    private static string t_career_precontract = nameof (career_precontract);
    private static string t_career_regenplayerattributes = nameof (career_regenplayerattributes);
    private static string t_career_scoutmission = nameof (career_scoutmission);
    private static string t_career_scouts = nameof (career_scouts);
    private static string t_career_squadranking = nameof (career_squadranking);
    private static string t_career_teamofweek = nameof (career_teamofweek);
    private static string t_career_transferlist = nameof (career_transferlist);
    private static string t_career_transferoffer = nameof (career_transferoffer);
    private static string t_career_trophies = nameof (career_trophies);
    private static string t_career_users = nameof (career_users);
    private static string t_career_youthplayerattributes = nameof (career_youthplayerattributes);
    private static string t_career_youthplayerhistory = nameof (career_youthplayerhistory);
    private static string t_career_youthplayers = nameof (career_youthplayers);
    private static string t_celebrations = nameof (celebrations);
    private static string t_clubcommentarynames = nameof (clubcommentarynames);
    private static string t_cmeventhistory = nameof (cmeventhistory);
    private static string t_cmteameventhistory = nameof (cmteameventhistory);
    private static string t_commentarynames = nameof (commentarynames);
    private static string t_competition = nameof (competition);
    private static string t_createplayer = nameof (createplayer);
    private static string t_createplayerpositiontemplates = nameof (createplayerpositiontemplates);
    private static string t_createplayerviews = nameof (createplayerviews);
    private static string t_customformations = nameof (customformations);
    private static string t_customteamstyles = nameof (customteamstyles);
    private static string t_cz_assets = nameof (cz_assets);
    private static string t_cz_leagues = nameof (cz_leagues);
    private static string t_cz_players = nameof (cz_players);
    private static string t_cz_teamkits = nameof (cz_teamkits);
    private static string t_cz_teams = nameof (cz_teams);
    private static string t_dcplayernames = nameof (dcplayernames);
    private static string t_dlcballs = nameof (dlcballs);
    private static string t_dlcboots = nameof (dlcboots);
    private static string t_dna = nameof (dna);
    private static string t_defaultteamdata = nameof (defaultteamdata);
    private static string t_default_teamsheets = nameof (default_teamsheets);
    private static string t_eatrax = nameof (eatrax);
    private static string t_editedplayernames = nameof (editedplayernames);
    private static string t_factory_teams = nameof (factory_teams);
    private static string t_fieldpositionboundingboxes = nameof (fieldpositionboundingboxes);
    private static string t_fifaGameSettings = nameof (fifaGameSettings);
    private static string t_fixtures = nameof (fixtures);
    private static string t_formations = nameof (formations);
    private static string t_leaguerefereelinks = nameof (leaguerefereelinks);
    private static string t_leagues = nameof (leagues);
    private static string t_leagueteamlinks = nameof (leagueteamlinks);
    private static string t_manager = nameof (manager);
    private static string t_mls_fixtures = nameof (mls_fixtures);
    private static string t_nations = nameof (nations);
    private static string t_persistent_events = nameof (persistent_events);
    private static string t_physio = nameof (physio);
    private static string t_player_grudgelove = nameof (player_grudgelove);
    private static string t_player_stats = nameof (player_stats);
    private static string t_playerboots = nameof (playerboots);
    private static string t_playerformdiff = nameof (playerformdiff);
    private static string t_playerloans = nameof (playerloans);
    private static string t_playernames = nameof (playernames);
    private static string t_players = nameof (players);
    private static string t_previousteam = nameof (previousteam);
    private static string t_referee = nameof (referee);
    private static string t_restrictedplayers = nameof (restrictedplayers);
    private static string t_rivals = nameof (rivals);
    private static string t_rowteamnationlinks = nameof (rowteamnationlinks);
    private static string t_shoecolors = nameof (shoecolors);
    private static string t_songplaylistlinks = nameof (songplaylistlinks);
    private static string t_stadiumassignments = nameof (stadiumassignments);
    private static string t_stadiums = nameof (stadiums);
    private static string t_starratingboundaries = nameof (starratingboundaries);
    private static string t_stories = nameof (stories);
    private static string t_team_lookup = nameof (team_lookup);
    private static string t_teamballs = nameof (teamballs);
    private static string t_teamformationteamstylelinks = nameof (teamformationteamstylelinks);
    private static string t_teamformdiff = nameof (teamformdiff);
    private static string t_teamkits = nameof (teamkits);
    private static string t_teamplayerlinks = nameof (teamplayerlinks);
    private static string t_teams = nameof (teams);
    private static string t_teamstadiumlinks = nameof (teamstadiumlinks);
    private static string t_teamstadiumlinkscache = nameof (teamstadiumlinkscache);
    private static string t_temp_arenacreateplayer = nameof (temp_arenacreateplayer);
    private static string t_temp_arenaplayer = nameof (temp_arenaplayer);
    private static string t_temp_arenaplayername = nameof (temp_arenaplayername);
    private static string t_temp_arenateam = nameof (temp_arenateam);
    private static string t_temp_arenateamplayerlinks = nameof (temp_arenateamplayerlinks);
    private static string t_temp_createplayer = nameof (temp_createplayer);
    private static string t_temp_formations = nameof (temp_formations);
    private static string t_temp_players = nameof (temp_players);
    private static string t_temp_teamplayerlinks = nameof (temp_teamplayerlinks);
    private static string t_temp_teams = nameof (temp_teams);
    private static string t_trainingteamplayerlinks = nameof (trainingteamplayerlinks);
    private static string t_trainingteamplayernames = nameof (trainingteamplayernames);
    private static string t_trainingteamplayers = nameof (trainingteamplayers);
    private static string t_transactionhistory = nameof (transactionhistory);
    private static string t_version = nameof (version);
    private static string t_videos = nameof (videos);
    public static int lang = 0;
    public static int defaultteamdata = -1;
    public static int default_teamsheets = -1;
    public static int balls;
    public static int career_extraplayerinfo;
    public static int career_matchexperience;
    public static int career_suspensions;
    public static int formupdate;
    public static int career_fixtureinfo;
    public static int fce_activeteams;
    public static int fce_weathersettings;
    public static int fce_statistics;
    public static int fce_standings;
    public static int fce_stageadvance;
    public static int fce_settings;
    public static int fce_scriptfunctions;
    public static int fce_scheduleinfo;
    public static int fce_fixtures;
    public static int fce_competitionteams;
    public static int fce_competitioninfo;
    public static int fce_compavgs;
    public static int fce_advancement;
    public static int player_growth_experience_points;
    public static int player_career;
    public static int experiencepoints;
    public static int finalstadiums;
    public static int tourn_team_manager;
    public static int tourn_settings;
    public static int tourn_rtsg;
    public static int tourn_manager_settings;
    public static int tourn_licensed_stages;
    public static int tourn_licensed;
    public static int specialteams;
    public static int achievements;
    public static int fifaUnlockables;
    public static int usability;
    public static int usability_functions;
    public static int virtualleagues;
    public static int BigAttendance;
    public static int MatchIntensity;
    public static int NoAttendance;
    public static int assetcryptokeys;
    public static int attributeprefpositionformula;
    public static int audionation;
    public static int audiostadium;
    public static int career_blacklist;
    public static int career_boardoutcomes;
    public static int career_calendar;
    public static int career_clinchedobjectives;
    public static int career_commonnames;
    public static int career_competitionprogress;
    public static int career_firstnames;
    public static int career_growthcurveinfo;
    public static int career_lastnames;
    public static int career_leagueballs;
    public static int career_loanbuy;
    public static int career_managerawards;
    public static int career_managerhistory;
    public static int career_managerinfo;
    public static int career_managerpref;
    public static int career_namesgroups;
    public static int career_news;
    public static int career_newsban;
    public static int career_newspicweights;
    public static int career_playasplayer;
    public static int career_playasplayerhistory;
    public static int career_playerawards;
    public static int career_playerbonusper;
    public static int career_playercontract;
    public static int career_playergrowthhistory;
    public static int career_playergrowthupdates;
    public static int career_playergrowthuserseason;
    public static int career_playermatchratinghistory;
    public static int career_precontract;
    public static int career_regenplayerattributes;
    public static int career_scoutmission;
    public static int career_scouts;
    public static int career_squadranking;
    public static int career_teamofweek;
    public static int career_transferlist;
    public static int career_transferoffer;
    public static int career_trophies;
    public static int career_users;
    public static int career_youthplayerattributes;
    public static int career_youthplayerhistory;
    public static int career_youthplayers;
    public static int celebrations;
    public static int clubcommentarynames;
    public static int cmeventhistory;
    public static int cmteameventhistory;
    public static int commentarynames;
    public static int competition;
    public static int createplayer;
    public static int createplayerpositiontemplates;
    public static int createplayerviews;
    public static int customformations;
    public static int customteamstyles;
    public static int cz_assets;
    public static int cz_leagues;
    public static int cz_players;
    public static int cz_teamkits;
    public static int cz_teams;
    public static int dcplayernames;
    public static int dlcballs;
    public static int dlcboots;
    public static int dna;
    public static int eatrax;
    public static int editedplayernames;
    public static int factory_teams;
    public static int fieldpositionboundingboxes;
    public static int fifaGameSettings;
    public static int fixtures;
    public static int formations;
    public static int leaguerefereelinks;
    public static int leagues;
    public static int leagueteamlinks;
    public static int manager;
    public static int mls_fixtures;
    public static int nations;
    public static int persistent_events;
    public static int physio;
    public static int player_grudgelove;
    public static int player_stats;
    public static int playerboots;
    public static int playerformdiff;
    public static int playerloans;
    public static int playernames;
    public static int players;
    public static int previousteam;
    public static int referee;
    public static int restrictedplayers;
    public static int rivals;
    public static int rowteamnationlinks;
    public static int shoecolors;
    public static int songplaylistlinks;
    public static int stadiumassignments;
    public static int stadiums;
    public static int starratingboundaries;
    public static int stories;
    public static int team_lookup;
    public static int teamballs;
    public static int teamformationteamstylelinks;
    public static int teamformdiff;
    public static int teamkits;
    public static int teamplayerlinks;
    public static int teams;
    public static int teamstadiumlinks;
    public static int teamstadiumlinkscache;
    public static int temp_arenacreateplayer;
    public static int temp_arenaplayer;
    public static int temp_arenaplayername;
    public static int temp_arenateam;
    public static int temp_arenateamplayerlinks;
    public static int temp_createplayer;
    public static int temp_formations;
    public static int temp_players;
    public static int temp_teamplayerlinks;
    public static int temp_teams;
    public static int trainingteamplayerlinks;
    public static int trainingteamplayernames;
    public static int trainingteamplayers;
    public static int transactionhistory;
    public static int version;
    public static int videos;

    public static bool InitTIAsFIFA12(DbFile fifaDbFile)
    {
      bool flag = true;
      TI.dcplayernames = fifaDbFile.GetTableIndex(TI.t_dcplayernames);
      TI.version = fifaDbFile.GetTableIndex(TI.t_version);
      TI.transactionhistory = fifaDbFile.GetTableIndex(TI.t_transactionhistory);
      TI.trainingteamplayers = fifaDbFile.GetTableIndex(TI.t_trainingteamplayers);
      TI.trainingteamplayernames = fifaDbFile.GetTableIndex(TI.t_trainingteamplayernames);
      TI.trainingteamplayerlinks = fifaDbFile.GetTableIndex(TI.t_trainingteamplayerlinks);
      TI.temp_teamplayerlinks = fifaDbFile.GetTableIndex(TI.t_temp_teamplayerlinks);
      TI.temp_teams = fifaDbFile.GetTableIndex(TI.t_temp_teams);
      TI.temp_formations = fifaDbFile.GetTableIndex(TI.t_temp_formations);
      TI.temp_players = fifaDbFile.GetTableIndex(TI.t_temp_players);
      TI.temp_arenaplayer = fifaDbFile.GetTableIndex(TI.t_temp_arenaplayer);
      TI.temp_arenaplayername = fifaDbFile.GetTableIndex(TI.t_temp_arenaplayername);
      TI.temp_arenateam = fifaDbFile.GetTableIndex(TI.t_temp_arenateam);
      TI.temp_arenateamplayerlinks = fifaDbFile.GetTableIndex(TI.t_temp_arenateamplayerlinks);
      TI.teams = fifaDbFile.GetTableIndex(TI.t_teams);
      TI.teamstadiumlinks = fifaDbFile.GetTableIndex(TI.t_teamstadiumlinks);
      TI.teamplayerlinks = fifaDbFile.GetTableIndex(TI.t_teamplayerlinks);
      TI.teamkits = fifaDbFile.GetTableIndex(TI.t_teamkits);
      TI.teamballs = fifaDbFile.GetTableIndex(TI.t_teamballs);
      TI.stadiums = fifaDbFile.GetTableIndex(TI.t_stadiums);
      TI.rowteamnationlinks = fifaDbFile.GetTableIndex(TI.t_rowteamnationlinks);
      TI.rivals = fifaDbFile.GetTableIndex(TI.t_rivals);
      TI.referee = fifaDbFile.GetTableIndex(TI.t_referee);
      TI.players = fifaDbFile.GetTableIndex(TI.t_players);
      TI.playernames = fifaDbFile.GetTableIndex(TI.t_playernames);
      TI.playerloans = fifaDbFile.GetTableIndex(TI.t_playerloans);
      TI.playerboots = fifaDbFile.GetTableIndex(TI.t_playerboots);
      TI.player_grudgelove = fifaDbFile.GetTableIndex(TI.t_player_grudgelove);
      TI.physio = fifaDbFile.GetTableIndex(TI.t_physio);
      TI.nations = fifaDbFile.GetTableIndex(TI.t_nations);
      TI.manager = fifaDbFile.GetTableIndex(TI.t_manager);
      TI.leagueteamlinks = fifaDbFile.GetTableIndex(TI.t_leagueteamlinks);
      TI.leagues = fifaDbFile.GetTableIndex(TI.t_leagues);
      TI.leaguerefereelinks = fifaDbFile.GetTableIndex(TI.t_leaguerefereelinks);
      TI.formupdate = fifaDbFile.GetTableIndex(TI.t_formupdate);
      TI.formations = fifaDbFile.GetTableIndex(TI.t_formations);
      TI.fieldpositionboundingboxes = fifaDbFile.GetTableIndex(TI.t_fieldpositionboundingboxes);
      TI.editedplayernames = fifaDbFile.GetTableIndex(TI.t_editedplayernames);
      TI.dna = fifaDbFile.GetTableIndex(TI.t_dna);
      TI.audionation = fifaDbFile.GetTableIndex(TI.t_audionation);
      TI.NoAttendance = fifaDbFile.GetTableIndex(TI.t_NoAttendance);
      TI.MatchIntensity = fifaDbFile.GetTableIndex(TI.t_MatchIntensity);
      TI.BigAttendance = fifaDbFile.GetTableIndex(TI.t_BigAttendance);
      TI.career_managerawards = fifaDbFile.GetTableIndex(TI.t_career_managerawards);
      TI.career_teamofweek = fifaDbFile.GetTableIndex(TI.t_career_teamofweek);
      TI.career_playerawards = fifaDbFile.GetTableIndex(TI.t_career_playerawards);
      TI.career_calendar = fifaDbFile.GetTableIndex(TI.t_career_calendar);
      TI.career_suspensions = fifaDbFile.GetTableIndex(TI.t_career_suspensions);
      TI.career_squadranking = fifaDbFile.GetTableIndex(TI.t_career_squadranking);
      TI.career_playermatchratinghistory = fifaDbFile.GetTableIndex(TI.t_career_playermatchratinghistory);
      TI.career_fixtureinfo = fifaDbFile.GetTableIndex(TI.t_career_fixtureinfo);
      TI.career_extraplayerinfo = fifaDbFile.GetTableIndex(TI.t_career_extraplayerinfo);
      TI.cmeventhistory = fifaDbFile.GetTableIndex(TI.t_cmeventhistory);
      TI.career_boardoutcomes = fifaDbFile.GetTableIndex(TI.t_career_boardoutcomes);
      TI.career_users = fifaDbFile.GetTableIndex(TI.t_career_users);
      TI.career_trophies = fifaDbFile.GetTableIndex(TI.t_career_trophies);
      TI.career_managerpref = fifaDbFile.GetTableIndex(TI.t_career_managerpref);
      TI.career_managerinfo = fifaDbFile.GetTableIndex(TI.t_career_managerinfo);
      TI.career_managerhistory = fifaDbFile.GetTableIndex(TI.t_career_managerhistory);
      TI.career_leagueballs = fifaDbFile.GetTableIndex(TI.t_career_leagueballs);
      TI.career_competitionprogress = fifaDbFile.GetTableIndex(TI.t_career_competitionprogress);
      TI.clubcommentarynames = fifaDbFile.GetTableIndex(TI.t_clubcommentarynames);
      TI.commentarynames = fifaDbFile.GetTableIndex(TI.t_commentarynames);
      TI.createplayer = fifaDbFile.GetTableIndex(TI.t_createplayer);
      TI.createplayerpositiontemplates = fifaDbFile.GetTableIndex(TI.t_createplayerpositiontemplates);
      TI.createplayerviews = fifaDbFile.GetTableIndex(TI.t_createplayerviews);
      TI.cz_assets = fifaDbFile.GetTableIndex(TI.t_cz_assets);
      TI.cz_teams = fifaDbFile.GetTableIndex(TI.t_cz_teams);
      TI.cz_teamkits = fifaDbFile.GetTableIndex(TI.t_cz_teamkits);
      TI.cz_players = fifaDbFile.GetTableIndex(TI.t_cz_players);
      TI.cz_leagues = fifaDbFile.GetTableIndex(TI.t_cz_leagues);
      TI.balls = fifaDbFile.GetTableIndex(TI.t_balls);
      TI.teamstadiumlinkscache = fifaDbFile.GetTableIndex(TI.t_teamstadiumlinkscache);
      TI.dlcboots = fifaDbFile.GetTableIndex(TI.t_dlcboots);
      TI.dlcballs = fifaDbFile.GetTableIndex(TI.t_dlcballs);
      TI.eatrax = fifaDbFile.GetTableIndex(TI.t_eatrax);
      TI.songplaylistlinks = fifaDbFile.GetTableIndex(TI.t_songplaylistlinks);
      TI.celebrations = fifaDbFile.GetTableIndex(TI.t_celebrations);
      TI.videos = fifaDbFile.GetTableIndex(TI.t_videos);
      TI.fifaGameSettings = fifaDbFile.GetTableIndex(TI.t_fifaGameSettings);
      TI.mls_fixtures = fifaDbFile.GetTableIndex(TI.t_mls_fixtures);
      TI.team_lookup = fifaDbFile.GetTableIndex(TI.t_team_lookup);
      TI.player_stats = fifaDbFile.GetTableIndex(TI.t_player_stats);
      TI.customformations = fifaDbFile.GetTableIndex(TI.t_customformations);
      TI.teamformationteamstylelinks = fifaDbFile.GetTableIndex(TI.t_teamformationteamstylelinks);
      TI.customteamstyles = fifaDbFile.GetTableIndex(TI.t_customteamstyles);
      TI.career_news = fifaDbFile.GetTableIndex(TI.t_career_news);
      TI.career_newspicweights = fifaDbFile.GetTableIndex(TI.t_career_newspicweights);
      TI.career_newsban = fifaDbFile.GetTableIndex(TI.t_career_newsban);
      TI.persistent_events = fifaDbFile.GetTableIndex(TI.t_persistent_events);
      TI.career_playasplayer = fifaDbFile.GetTableIndex(TI.t_career_playasplayer);
      TI.career_playerbonusper = fifaDbFile.GetTableIndex(TI.t_career_playerbonusper);
      TI.career_playasplayerhistory = fifaDbFile.GetTableIndex(TI.t_career_playasplayerhistory);
      TI.career_growthcurveinfo = fifaDbFile.GetTableIndex(TI.t_career_growthcurveinfo);
      TI.player_career = fifaDbFile.GetTableIndex(TI.t_player_career);
      TI.player_growth_experience_points = fifaDbFile.GetTableIndex(TI.t_player_growth_experience_points);
      TI.experiencepoints = fifaDbFile.GetTableIndex(TI.t_experiencepoints);
      TI.career_playergrowthuserseason = fifaDbFile.GetTableIndex(TI.t_career_playergrowthuserseason);
      TI.career_playergrowthupdates = fifaDbFile.GetTableIndex(TI.t_career_playergrowthupdates);
      TI.career_playergrowthhistory = fifaDbFile.GetTableIndex(TI.t_career_playergrowthhistory);
      TI.career_matchexperience = fifaDbFile.GetTableIndex(TI.t_career_matchexperience);
      TI.specialteams = fifaDbFile.GetTableIndex(TI.t_specialteams);
      TI.stadiumassignments = fifaDbFile.GetTableIndex(TI.t_stadiumassignments);
      TI.factory_teams = fifaDbFile.GetTableIndex(TI.t_factory_teams);
      TI.temp_arenacreateplayer = fifaDbFile.GetTableIndex(TI.t_temp_arenacreateplayer);
      TI.temp_createplayer = fifaDbFile.GetTableIndex(TI.t_temp_createplayer);
      TI.usability_functions = fifaDbFile.GetTableIndex(TI.t_usability_functions);
      TI.usability = fifaDbFile.GetTableIndex(TI.t_usability);
      TI.virtualleagues = fifaDbFile.GetTableIndex(TI.t_virtualleagues);
      TI.career_blacklist = fifaDbFile.GetTableIndex(TI.t_career_blacklist);
      TI.career_transferoffer = fifaDbFile.GetTableIndex(TI.t_career_transferoffer);
      TI.career_transferlist = fifaDbFile.GetTableIndex(TI.t_career_transferlist);
      TI.career_playercontract = fifaDbFile.GetTableIndex(TI.t_career_playercontract);
      TI.career_loanbuy = fifaDbFile.GetTableIndex(TI.t_career_loanbuy);
      TI.career_commonnames = fifaDbFile.GetTableIndex(TI.t_career_commonnames);
      TI.career_youthplayers = fifaDbFile.GetTableIndex(TI.t_career_youthplayers);
      TI.career_youthplayerhistory = fifaDbFile.GetTableIndex(TI.t_career_youthplayershistory);
      TI.career_youthplayerattributes = fifaDbFile.GetTableIndex(TI.t_career_youthplayersattributes);
      TI.career_scouts = fifaDbFile.GetTableIndex(TI.t_career_scouts);
      TI.career_scoutmission = fifaDbFile.GetTableIndex(TI.t_career_scoutmission);
      TI.career_namesgroups = fifaDbFile.GetTableIndex(TI.t_career_namesgroups);
      TI.career_lastnames = fifaDbFile.GetTableIndex(TI.t_career_lastnames);
      TI.career_firstnames = fifaDbFile.GetTableIndex(TI.t_career_firstnames);
      return flag;
    }

    public static bool InitTIAsFIFA13(DbFile fifaDbFile)
    {
      bool flag = true;
      TI.fixtures = fifaDbFile.GetTableIndex(TI.t_fixtures);
      TI.player_stats = fifaDbFile.GetTableIndex(TI.t_player_stats);
      TI.team_lookup = fifaDbFile.GetTableIndex(TI.t_team_lookup);
      TI.assetcryptokeys = fifaDbFile.GetTableIndex(TI.t_assetcryptokeys);
      TI.version = fifaDbFile.GetTableIndex(TI.t_version);
      TI.transactionhistory = fifaDbFile.GetTableIndex(TI.t_transactionhistory);
      TI.trainingteamplayers = fifaDbFile.GetTableIndex(TI.t_trainingteamplayers);
      TI.trainingteamplayernames = fifaDbFile.GetTableIndex(TI.t_trainingteamplayernames);
      TI.trainingteamplayerlinks = fifaDbFile.GetTableIndex(TI.t_trainingteamplayerlinks);
      TI.temp_teams = fifaDbFile.GetTableIndex(TI.t_temp_teams);
      TI.temp_teamplayerlinks = fifaDbFile.GetTableIndex(TI.t_temp_teamplayerlinks);
      TI.temp_players = fifaDbFile.GetTableIndex(TI.t_temp_players);
      TI.temp_formations = fifaDbFile.GetTableIndex(TI.t_temp_formations);
      TI.temp_arenateamplayerlinks = fifaDbFile.GetTableIndex(TI.t_temp_arenateamplayerlinks);
      TI.temp_arenateam = fifaDbFile.GetTableIndex(TI.t_temp_arenateam);
      TI.temp_arenaplayername = fifaDbFile.GetTableIndex(TI.t_temp_arenaplayername);
      TI.temp_arenaplayer = fifaDbFile.GetTableIndex(TI.t_temp_arenaplayer);
      TI.teamstadiumlinks = fifaDbFile.GetTableIndex(TI.t_teamstadiumlinks);
      TI.teams = fifaDbFile.GetTableIndex(TI.t_teams);
      TI.teamplayerlinks = fifaDbFile.GetTableIndex(TI.t_teamplayerlinks);
      TI.teamkits = fifaDbFile.GetTableIndex(TI.t_teamkits);
      TI.teamformdiff = fifaDbFile.GetTableIndex(TI.t_teamformdiff);
      TI.teamballs = fifaDbFile.GetTableIndex(TI.t_teamballs);
      TI.stories = fifaDbFile.GetTableIndex(TI.t_stories);
      TI.starratingboundaries = fifaDbFile.GetTableIndex(TI.t_starratingboundaries);
      TI.stadiums = fifaDbFile.GetTableIndex(TI.t_stadiums);
      TI.shoecolors = fifaDbFile.GetTableIndex(TI.t_shoecolors);
      TI.rowteamnationlinks = fifaDbFile.GetTableIndex(TI.t_rowteamnationlinks);
      TI.rivals = fifaDbFile.GetTableIndex(TI.t_rivals);
      TI.restrictedplayers = fifaDbFile.GetTableIndex(TI.t_restrictedplayers);
      TI.referee = fifaDbFile.GetTableIndex(TI.t_referee);
      TI.previousteam = fifaDbFile.GetTableIndex(TI.t_previousteam);
      TI.players = fifaDbFile.GetTableIndex(TI.t_players);
      TI.playernames = fifaDbFile.GetTableIndex(TI.t_playernames);
      TI.playerloans = fifaDbFile.GetTableIndex(TI.t_playerloans);
      TI.playerformdiff = fifaDbFile.GetTableIndex(TI.t_playerformdiff);
      TI.playerboots = fifaDbFile.GetTableIndex(TI.t_playerboots);
      TI.player_grudgelove = fifaDbFile.GetTableIndex(TI.t_player_grudgelove);
      TI.physio = fifaDbFile.GetTableIndex(TI.t_physio);
      TI.nations = fifaDbFile.GetTableIndex(TI.t_nations);
      TI.manager = fifaDbFile.GetTableIndex(TI.t_manager);
      TI.leagueteamlinks = fifaDbFile.GetTableIndex(TI.t_leagueteamlinks);
      TI.leagues = fifaDbFile.GetTableIndex(TI.t_leagues);
      TI.leaguerefereelinks = fifaDbFile.GetTableIndex(TI.t_leaguerefereelinks);
      TI.formupdate = fifaDbFile.GetTableIndex(TI.t_formupdate);
      TI.formations = fifaDbFile.GetTableIndex(TI.t_formations);
      TI.fieldpositionboundingboxes = fifaDbFile.GetTableIndex(TI.t_fieldpositionboundingboxes);
      TI.editedplayernames = fifaDbFile.GetTableIndex(TI.t_editedplayernames);
      TI.dna = fifaDbFile.GetTableIndex(TI.t_dna);
      TI.dcplayernames = fifaDbFile.GetTableIndex(TI.t_dcplayernames);
      TI.customformations = fifaDbFile.GetTableIndex(TI.t_customformations);
      TI.competition = fifaDbFile.GetTableIndex(TI.t_competition);
      TI.career_lastnames = fifaDbFile.GetTableIndex(TI.t_career_lastnames);
      TI.career_firstnames = fifaDbFile.GetTableIndex(TI.t_career_firstnames);
      TI.career_commonnames = fifaDbFile.GetTableIndex(TI.t_career_commonnames);
      TI.attributeprefpositionformula = fifaDbFile.GetTableIndex(TI.t_attributeprefpositionformula);
      TI.audionation = fifaDbFile.GetTableIndex(TI.t_audionation);
      TI.NoAttendance = fifaDbFile.GetTableIndex(TI.t_NoAttendance);
      TI.MatchIntensity = fifaDbFile.GetTableIndex(TI.t_MatchIntensity);
      TI.BigAttendance = fifaDbFile.GetTableIndex(TI.t_BigAttendance);
      TI.audiostadium = fifaDbFile.GetTableIndex(TI.t_audiostadium);
      TI.career_managerawards = fifaDbFile.GetTableIndex(TI.t_career_managerawards);
      TI.career_teamofweek = fifaDbFile.GetTableIndex(TI.t_career_teamofweek);
      TI.career_playerawards = fifaDbFile.GetTableIndex(TI.t_career_playerawards);
      TI.career_calendar = fifaDbFile.GetTableIndex(TI.t_career_calendar);
      TI.career_squadranking = fifaDbFile.GetTableIndex(TI.t_career_squadranking);
      TI.career_playermatchratinghistory = fifaDbFile.GetTableIndex(TI.t_career_playermatchratinghistory);
      TI.career_fixtureinfo = fifaDbFile.GetTableIndex(TI.t_career_fixtureinfo);
      TI.career_clinchedobjectives = fifaDbFile.GetTableIndex(TI.t_career_clinchedobjectives);
      TI.cmeventhistory = fifaDbFile.GetTableIndex(TI.t_cmeventhistory);
      TI.cmteameventhistory = fifaDbFile.GetTableIndex(TI.t_cmteameventhistory);
      TI.career_boardoutcomes = fifaDbFile.GetTableIndex(TI.t_career_boardoutcomes);
      TI.career_users = fifaDbFile.GetTableIndex(TI.t_career_users);
      TI.career_trophies = fifaDbFile.GetTableIndex(TI.t_career_trophies);
      TI.career_managerpref = fifaDbFile.GetTableIndex(TI.t_career_managerpref);
      TI.career_managerinfo = fifaDbFile.GetTableIndex(TI.t_career_managerinfo);
      TI.career_managerhistory = fifaDbFile.GetTableIndex(TI.t_career_managerhistory);
      TI.career_leagueballs = fifaDbFile.GetTableIndex(TI.t_career_leagueballs);
      TI.career_competitionprogress = fifaDbFile.GetTableIndex(TI.t_career_competitionprogress);
      TI.clubcommentarynames = fifaDbFile.GetTableIndex(TI.t_clubcommentarynames);
      TI.createplayerviews = fifaDbFile.GetTableIndex(TI.t_createplayerviews);
      TI.createplayerpositiontemplates = fifaDbFile.GetTableIndex(TI.t_createplayerpositiontemplates);
      TI.createplayer = fifaDbFile.GetTableIndex(TI.t_createplayer);
      TI.commentarynames = fifaDbFile.GetTableIndex(TI.t_commentarynames);
      TI.cz_assets = fifaDbFile.GetTableIndex(TI.t_cz_assets);
      TI.cz_teams = fifaDbFile.GetTableIndex(TI.t_cz_teams);
      TI.cz_teamkits = fifaDbFile.GetTableIndex(TI.t_cz_teamkits);
      TI.cz_players = fifaDbFile.GetTableIndex(TI.t_cz_players);
      TI.cz_leagues = fifaDbFile.GetTableIndex(TI.t_cz_leagues);
      TI.dlcballs = fifaDbFile.GetTableIndex(TI.t_dlcballs);
      TI.teamstadiumlinkscache = fifaDbFile.GetTableIndex(TI.t_teamstadiumlinkscache);
      TI.dlcboots = fifaDbFile.GetTableIndex(TI.t_dlcboots);
      TI.eatrax = fifaDbFile.GetTableIndex(TI.t_eatrax);
      TI.songplaylistlinks = fifaDbFile.GetTableIndex(TI.t_songplaylistlinks);
      TI.celebrations = fifaDbFile.GetTableIndex(TI.t_celebrations);
      TI.videos = fifaDbFile.GetTableIndex(TI.t_videos);
      TI.fce_activeteams = fifaDbFile.GetTableIndex(TI.t_fce_activeteams);
      TI.fce_weathersettings = fifaDbFile.GetTableIndex(TI.t_fce_weathersettings);
      TI.fce_statistics = fifaDbFile.GetTableIndex(TI.t_fce_statistics);
      TI.fce_standings = fifaDbFile.GetTableIndex(TI.t_fce_standings);
      TI.fce_stageadvance = fifaDbFile.GetTableIndex(TI.t_fce_stageadvance);
      TI.fce_settings = fifaDbFile.GetTableIndex(TI.t_fce_settings);
      TI.fce_scriptfunctions = fifaDbFile.GetTableIndex(TI.t_fce_scriptfunctions);
      TI.fce_scheduleinfo = fifaDbFile.GetTableIndex(TI.t_fce_scheduleinfo);
      TI.fce_fixtures = fifaDbFile.GetTableIndex(TI.t_fce_fixtures);
      TI.fce_competitionteams = fifaDbFile.GetTableIndex(TI.t_fce_competitionteams);
      TI.fce_competitioninfo = fifaDbFile.GetTableIndex(TI.t_fce_competitioninfo);
      TI.fce_compavgs = fifaDbFile.GetTableIndex(TI.t_fce_compavgs);
      TI.fce_advancement = fifaDbFile.GetTableIndex(TI.t_fce_advancement);
      TI.fifaGameSettings = fifaDbFile.GetTableIndex(TI.t_fifaGameSettings);
      TI.mls_fixtures = fifaDbFile.GetTableIndex(TI.t_mls_fixtures);
      TI.customteamstyles = fifaDbFile.GetTableIndex(TI.t_customteamstyles);
      TI.teamformationteamstylelinks = fifaDbFile.GetTableIndex(TI.t_teamformationteamstylelinks);
      TI.career_news = fifaDbFile.GetTableIndex(TI.t_career_news);
      TI.career_newspicweights = fifaDbFile.GetTableIndex(TI.t_career_newspicweights);
      TI.career_newsban = fifaDbFile.GetTableIndex(TI.t_career_newsban);
      TI.persistent_events = fifaDbFile.GetTableIndex(TI.t_persistent_events);
      TI.career_playasplayer = fifaDbFile.GetTableIndex(TI.t_career_playasplayer);
      TI.career_playerbonusper = fifaDbFile.GetTableIndex(TI.t_career_playerbonusper);
      TI.career_playasplayerhistory = fifaDbFile.GetTableIndex(TI.t_career_playasplayerhistory);
      TI.career_growthcurveinfo = fifaDbFile.GetTableIndex(TI.t_career_growthcurveinfo);
      TI.player_growth_experience_points = fifaDbFile.GetTableIndex(TI.t_player_growth_experience_points);
      TI.player_career = fifaDbFile.GetTableIndex(TI.t_player_career);
      TI.experiencepoints = fifaDbFile.GetTableIndex(TI.t_experiencepoints);
      TI.career_playergrowthuserseason = fifaDbFile.GetTableIndex(TI.t_career_playergrowthuserseason);
      TI.career_playergrowthupdates = fifaDbFile.GetTableIndex(TI.t_career_playergrowthupdates);
      TI.career_playergrowthhistory = fifaDbFile.GetTableIndex(TI.t_career_playergrowthhistory);
      TI.finalstadiums = fifaDbFile.GetTableIndex(TI.t_finalstadiums);
      TI.tourn_team_manager = fifaDbFile.GetTableIndex(TI.t_tourn_team_manager);
      TI.tourn_settings = fifaDbFile.GetTableIndex(TI.t_tourn_settings);
      TI.tourn_rtsg = fifaDbFile.GetTableIndex(TI.t_tourn_rtsg);
      TI.tourn_manager_settings = fifaDbFile.GetTableIndex(TI.t_tourn_manager_settings);
      TI.tourn_licensed_stages = fifaDbFile.GetTableIndex(TI.t_tourn_licensed_stages);
      TI.tourn_licensed = fifaDbFile.GetTableIndex(TI.t_tourn_licensed);
      TI.specialteams = fifaDbFile.GetTableIndex(TI.t_specialteams);
      TI.stadiumassignments = fifaDbFile.GetTableIndex(TI.t_stadiumassignments);
      TI.factory_teams = fifaDbFile.GetTableIndex(TI.t_factory_teams);
      TI.temp_createplayer = fifaDbFile.GetTableIndex(TI.t_temp_createplayer);
      TI.temp_arenacreateplayer = fifaDbFile.GetTableIndex(TI.t_temp_arenacreateplayer);
      TI.career_blacklist = fifaDbFile.GetTableIndex(TI.t_career_blacklist);
      TI.career_transferoffer = fifaDbFile.GetTableIndex(TI.t_career_transferoffer);
      TI.career_transferlist = fifaDbFile.GetTableIndex(TI.t_career_transferlist);
      TI.career_playercontract = fifaDbFile.GetTableIndex(TI.t_career_playercontract);
      TI.career_loanbuy = fifaDbFile.GetTableIndex(TI.t_career_loanbuy);
      TI.achievements = fifaDbFile.GetTableIndex(TI.t_achievements);
      TI.fifaUnlockables = fifaDbFile.GetTableIndex(TI.t_fifaUnlockables);
      TI.usability = fifaDbFile.GetTableIndex(TI.t_usability);
      TI.usability_functions = fifaDbFile.GetTableIndex(TI.t_usability_functions);
      TI.virtualleagues = fifaDbFile.GetTableIndex(TI.t_virtualleagues);
      TI.career_namesgroups = fifaDbFile.GetTableIndex(TI.t_career_namesgroups);
      TI.career_youthplayers = fifaDbFile.GetTableIndex(TI.t_career_youthplayers);
      TI.career_youthplayerhistory = fifaDbFile.GetTableIndex(TI.t_career_youthplayerhistory);
      TI.career_youthplayerattributes = fifaDbFile.GetTableIndex(TI.t_career_youthplayerattributes);
      TI.career_scouts = fifaDbFile.GetTableIndex(TI.t_career_scouts);
      TI.career_scoutmission = fifaDbFile.GetTableIndex(TI.t_career_scoutmission);
      TI.career_regenplayerattributes = fifaDbFile.GetTableIndex(TI.t_career_regenplayerattributes);
      return flag;
    }

    public static bool InitTIAsFIFA14(DbFile fifaDbFile)
    {
      bool flag = true;
      TI.BigAttendance = fifaDbFile.GetTableIndex(TI.t_BigAttendance);
      TI.MatchIntensity = fifaDbFile.GetTableIndex(TI.t_MatchIntensity);
      TI.NoAttendance = fifaDbFile.GetTableIndex(TI.t_NoAttendance);
      TI.assetcryptokeys = fifaDbFile.GetTableIndex(TI.t_assetcryptokeys);
      TI.attributeprefpositionformula = fifaDbFile.GetTableIndex(TI.t_attributeprefpositionformula);
      TI.audionation = fifaDbFile.GetTableIndex(TI.t_audionation);
      TI.audiostadium = fifaDbFile.GetTableIndex(TI.t_audiostadium);
      TI.career_blacklist = fifaDbFile.GetTableIndex(TI.t_career_blacklist);
      TI.career_boardoutcomes = fifaDbFile.GetTableIndex(TI.t_career_boardoutcomes);
      TI.career_calendar = fifaDbFile.GetTableIndex(TI.t_career_calendar);
      TI.career_clinchedobjectives = fifaDbFile.GetTableIndex(TI.t_career_clinchedobjectives);
      TI.career_commonnames = fifaDbFile.GetTableIndex(TI.t_career_commonnames);
      TI.career_competitionprogress = fifaDbFile.GetTableIndex(TI.t_career_competitionprogress);
      TI.career_firstnames = fifaDbFile.GetTableIndex(TI.t_career_firstnames);
      TI.career_growthcurveinfo = fifaDbFile.GetTableIndex(TI.t_career_growthcurveinfo);
      TI.career_lastnames = fifaDbFile.GetTableIndex(TI.t_career_lastnames);
      TI.career_leagueballs = fifaDbFile.GetTableIndex(TI.t_career_leagueballs);
      TI.career_loanbuy = fifaDbFile.GetTableIndex(TI.t_career_loanbuy);
      TI.career_managerawards = fifaDbFile.GetTableIndex(TI.t_career_managerawards);
      TI.career_managerhistory = fifaDbFile.GetTableIndex(TI.t_career_managerhistory);
      TI.career_managerinfo = fifaDbFile.GetTableIndex(TI.t_career_managerinfo);
      TI.career_managerpref = fifaDbFile.GetTableIndex(TI.t_career_managerpref);
      TI.career_namesgroups = fifaDbFile.GetTableIndex(TI.t_career_namesgroups);
      TI.career_news = fifaDbFile.GetTableIndex(TI.t_career_news);
      TI.career_newsban = fifaDbFile.GetTableIndex(TI.t_career_newsban);
      TI.career_newspicweights = fifaDbFile.GetTableIndex(TI.t_career_newspicweights);
      TI.career_playasplayer = fifaDbFile.GetTableIndex(TI.t_career_playasplayer);
      TI.career_playasplayerhistory = fifaDbFile.GetTableIndex(TI.t_career_playasplayerhistory);
      TI.career_playerawards = fifaDbFile.GetTableIndex(TI.t_career_playerawards);
      TI.career_playerbonusper = fifaDbFile.GetTableIndex(TI.t_career_playerbonusper);
      TI.career_playercontract = fifaDbFile.GetTableIndex(TI.t_career_playercontract);
      TI.career_playergrowthhistory = fifaDbFile.GetTableIndex(TI.t_career_playergrowthhistory);
      TI.career_playergrowthupdates = fifaDbFile.GetTableIndex(TI.t_career_playergrowthupdates);
      TI.career_playergrowthuserseason = fifaDbFile.GetTableIndex(TI.t_career_playergrowthuserseason);
      TI.career_playermatchratinghistory = fifaDbFile.GetTableIndex(TI.t_career_playermatchratinghistory);
      TI.career_precontract = fifaDbFile.GetTableIndex(TI.t_career_precontract);
      TI.career_regenplayerattributes = fifaDbFile.GetTableIndex(TI.t_career_regenplayerattributes);
      TI.career_scoutmission = fifaDbFile.GetTableIndex(TI.t_career_scoutmission);
      TI.career_scouts = fifaDbFile.GetTableIndex(TI.t_career_scouts);
      TI.career_squadranking = fifaDbFile.GetTableIndex(TI.t_career_squadranking);
      TI.career_teamofweek = fifaDbFile.GetTableIndex(TI.t_career_teamofweek);
      TI.career_transferlist = fifaDbFile.GetTableIndex(TI.t_career_transferlist);
      TI.career_transferoffer = fifaDbFile.GetTableIndex(TI.t_career_transferoffer);
      TI.career_trophies = fifaDbFile.GetTableIndex(TI.t_career_trophies);
      TI.career_users = fifaDbFile.GetTableIndex(TI.t_career_users);
      TI.career_youthplayerattributes = fifaDbFile.GetTableIndex(TI.t_career_youthplayerattributes);
      TI.career_youthplayerhistory = fifaDbFile.GetTableIndex(TI.t_career_youthplayerhistory);
      TI.career_youthplayers = fifaDbFile.GetTableIndex(TI.t_career_youthplayers);
      TI.celebrations = fifaDbFile.GetTableIndex(TI.t_celebrations);
      TI.clubcommentarynames = fifaDbFile.GetTableIndex(TI.t_clubcommentarynames);
      TI.cmeventhistory = fifaDbFile.GetTableIndex(TI.t_cmeventhistory);
      TI.cmteameventhistory = fifaDbFile.GetTableIndex(TI.t_cmteameventhistory);
      TI.commentarynames = fifaDbFile.GetTableIndex(TI.t_commentarynames);
      TI.competition = fifaDbFile.GetTableIndex(TI.t_competition);
      TI.createplayer = fifaDbFile.GetTableIndex(TI.t_createplayer);
      TI.createplayerpositiontemplates = fifaDbFile.GetTableIndex(TI.t_createplayerpositiontemplates);
      TI.createplayerviews = fifaDbFile.GetTableIndex(TI.t_createplayerviews);
      TI.customformations = fifaDbFile.GetTableIndex(TI.t_customformations);
      TI.customteamstyles = fifaDbFile.GetTableIndex(TI.t_customteamstyles);
      TI.cz_assets = fifaDbFile.GetTableIndex(TI.t_cz_assets);
      TI.cz_leagues = fifaDbFile.GetTableIndex(TI.t_cz_leagues);
      TI.cz_players = fifaDbFile.GetTableIndex(TI.t_cz_players);
      TI.cz_teamkits = fifaDbFile.GetTableIndex(TI.t_cz_teamkits);
      TI.cz_teams = fifaDbFile.GetTableIndex(TI.t_cz_teams);
      TI.dcplayernames = fifaDbFile.GetTableIndex(TI.t_dcplayernames);
      TI.dlcballs = fifaDbFile.GetTableIndex(TI.t_dlcballs);
      TI.dlcboots = fifaDbFile.GetTableIndex(TI.t_dlcboots);
      TI.dna = fifaDbFile.GetTableIndex(TI.t_dna);
      TI.defaultteamdata = fifaDbFile.GetTableIndex(TI.t_defaultteamdata);
      TI.default_teamsheets = fifaDbFile.GetTableIndex(TI.t_default_teamsheets);
      TI.eatrax = fifaDbFile.GetTableIndex(TI.t_eatrax);
      TI.editedplayernames = fifaDbFile.GetTableIndex(TI.t_editedplayernames);
      TI.factory_teams = fifaDbFile.GetTableIndex(TI.t_factory_teams);
      TI.fieldpositionboundingboxes = fifaDbFile.GetTableIndex(TI.t_fieldpositionboundingboxes);
      TI.fifaGameSettings = fifaDbFile.GetTableIndex(TI.t_fifaGameSettings);
      TI.fixtures = fifaDbFile.GetTableIndex(TI.t_fixtures);
      TI.formations = fifaDbFile.GetTableIndex(TI.t_formations);
      TI.leaguerefereelinks = fifaDbFile.GetTableIndex(TI.t_leaguerefereelinks);
      TI.leagues = fifaDbFile.GetTableIndex(TI.t_leagues);
      TI.leagueteamlinks = fifaDbFile.GetTableIndex(TI.t_leagueteamlinks);
      TI.manager = fifaDbFile.GetTableIndex(TI.t_manager);
      TI.mls_fixtures = fifaDbFile.GetTableIndex(TI.t_mls_fixtures);
      TI.nations = fifaDbFile.GetTableIndex(TI.t_nations);
      TI.persistent_events = fifaDbFile.GetTableIndex(TI.t_persistent_events);
      TI.physio = fifaDbFile.GetTableIndex(TI.t_physio);
      TI.player_grudgelove = fifaDbFile.GetTableIndex(TI.t_player_grudgelove);
      TI.player_stats = fifaDbFile.GetTableIndex(TI.t_player_stats);
      TI.playerboots = fifaDbFile.GetTableIndex(TI.t_playerboots);
      TI.playerformdiff = fifaDbFile.GetTableIndex(TI.t_playerformdiff);
      TI.playerloans = fifaDbFile.GetTableIndex(TI.t_playerloans);
      TI.playernames = fifaDbFile.GetTableIndex(TI.t_playernames);
      TI.players = fifaDbFile.GetTableIndex(TI.t_players);
      TI.previousteam = fifaDbFile.GetTableIndex(TI.t_previousteam);
      TI.referee = fifaDbFile.GetTableIndex(TI.t_referee);
      TI.restrictedplayers = fifaDbFile.GetTableIndex(TI.t_restrictedplayers);
      TI.rivals = fifaDbFile.GetTableIndex(TI.t_rivals);
      TI.rowteamnationlinks = fifaDbFile.GetTableIndex(TI.t_rowteamnationlinks);
      TI.shoecolors = fifaDbFile.GetTableIndex(TI.t_shoecolors);
      TI.songplaylistlinks = fifaDbFile.GetTableIndex(TI.t_songplaylistlinks);
      TI.stadiumassignments = fifaDbFile.GetTableIndex(TI.t_stadiumassignments);
      TI.stadiums = fifaDbFile.GetTableIndex(TI.t_stadiums);
      TI.starratingboundaries = fifaDbFile.GetTableIndex(TI.t_starratingboundaries);
      TI.stories = fifaDbFile.GetTableIndex(TI.t_stories);
      TI.team_lookup = fifaDbFile.GetTableIndex(TI.t_team_lookup);
      TI.teamballs = fifaDbFile.GetTableIndex(TI.t_teamballs);
      TI.teamformationteamstylelinks = fifaDbFile.GetTableIndex(TI.t_teamformationteamstylelinks);
      TI.teamformdiff = fifaDbFile.GetTableIndex(TI.t_teamformdiff);
      TI.teamkits = fifaDbFile.GetTableIndex(TI.t_teamkits);
      TI.teamplayerlinks = fifaDbFile.GetTableIndex(TI.t_teamplayerlinks);
      TI.teams = fifaDbFile.GetTableIndex(TI.t_teams);
      TI.teamstadiumlinks = fifaDbFile.GetTableIndex(TI.t_teamstadiumlinks);
      TI.teamstadiumlinkscache = fifaDbFile.GetTableIndex(TI.t_teamstadiumlinkscache);
      TI.temp_arenacreateplayer = fifaDbFile.GetTableIndex(TI.t_temp_arenacreateplayer);
      TI.temp_arenaplayer = fifaDbFile.GetTableIndex(TI.t_temp_arenaplayer);
      TI.temp_arenaplayername = fifaDbFile.GetTableIndex(TI.t_temp_arenaplayername);
      TI.temp_arenateam = fifaDbFile.GetTableIndex(TI.t_temp_arenateam);
      TI.temp_arenateamplayerlinks = fifaDbFile.GetTableIndex(TI.t_temp_arenateamplayerlinks);
      TI.temp_createplayer = fifaDbFile.GetTableIndex(TI.t_temp_createplayer);
      TI.temp_formations = fifaDbFile.GetTableIndex(TI.t_temp_formations);
      TI.temp_players = fifaDbFile.GetTableIndex(TI.t_temp_players);
      TI.temp_teamplayerlinks = fifaDbFile.GetTableIndex(TI.t_temp_teamplayerlinks);
      TI.temp_teams = fifaDbFile.GetTableIndex(TI.t_temp_teams);
      TI.trainingteamplayerlinks = fifaDbFile.GetTableIndex(TI.t_trainingteamplayerlinks);
      TI.trainingteamplayernames = fifaDbFile.GetTableIndex(TI.t_trainingteamplayernames);
      TI.trainingteamplayers = fifaDbFile.GetTableIndex(TI.t_trainingteamplayers);
      TI.transactionhistory = fifaDbFile.GetTableIndex(TI.t_transactionhistory);
      TI.version = fifaDbFile.GetTableIndex(TI.t_version);
      TI.videos = fifaDbFile.GetTableIndex(TI.t_videos);
      return flag;
    }
  }
}
